

export const TECH_ACTION = {
    REQUEST: 'TECH_REQUEST',
    SUCCESS: 'TECH_SUCCESS',
    FAILURE: 'TECH_FAILURE'
}

export const ALL_TECH_ACTION = {
    REQUEST: 'ALL_TECH_REQUEST',
    SUCCESS: 'ALL_TECH_SUCCESS',
    FAILURE: 'ALL_TECH_FAILURE'
}

export const VALIDATE_USER_ACTION = {
    REQUEST: 'VALIDATE_USER_ACTION_REQUEST',
    SUCCESS: 'VALIDATE_USER_ACTION_SUCCESS',
    FAILURE: 'VALIDATE_USER_ACTION_FAILURE'
}

export const USER_ACTION = {
    REQUEST: 'ALL_TECH_REQUEST_REQUEST',
    SUCCESS: 'ALL_TECH_SUCCESS_SUCCESS',
    FAILURE: 'ALL_TECH_FAILURE_FAILURE'
}






