
export const GET_ALL_SILVER_ACTION = {
    REQUEST: 'GET_ALL_SILVER_ACTION_REQUEST',
    SUCCESS: 'GET_ALL_SILVER_ACTION_SUCCESS',
    FAILURE: 'GET_ALL_SILVER_ACTION_FAILURE'
}
export const GET_SILVER_ACTION = {
    REQUEST: 'GET_SILVER_ACTION_REQUEST',
    SUCCESS: 'GET_SILVER_ACTION_SUCCESS',
    FAILURE: 'GET_SILVER_ACTION_FAILURE'
}








